/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import modelo.Movement;
import modelo.Pokemon;
import poketac.PokeTAC;

/**
 *
 * @author Usuario
 */
public class BattleScreen extends javax.swing.JPanel{
    private MainWindow mw;
    private final PokeTAC logicMan;
    private PokemonStatus pc;
    private PokemonStatus user;


    public BattleScreen(MainWindow mw, PokeTAC logicMan) {
        initComponents();
        this.mw = mw;
        this.logicMan = logicMan;
        initPokemonStatus();
    }
    
    private void initPokemonStatus(){
        user = new PokemonStatus(logicMan.getBattle().getEntrenadores().get(0).getActivePokemon());
        pc = new PokemonStatus(logicMan.getBattle().getEntrenadores().get(1).getActivePokemon());
        
        pnlUser.add(user);
        pnlUser.add(new Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767)));
        
        pnlAI.add(new Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767)));
        pnlAI.add(pc);
        
    }
    
    public void advanceTurn(){
        logicMan.getBattle().proccessTurnLogic();
        repaint();
        if(logicMan.getBattle().isBattlerOver()){
            JOptionPane.showMessageDialog(pnlActions, "Juego terminado.");
        }else{
            if(!logicMan.isUserTurn()){
                logicMan.selectAIMove();
                advanceTurn();
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaLog = new javax.swing.JTextArea();
        pnlActions = new javax.swing.JPanel();
        btnFight = new javax.swing.JButton();
        btnPKMN = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        pnlBattle = new javax.swing.JPanel();
        pnlUser = new javax.swing.JPanel();
        pnlAI = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlBottom.setLayout(new java.awt.BorderLayout(10, 0));

        txtaLog.setEditable(false);
        txtaLog.setColumns(20);
        txtaLog.setRows(5);
        jScrollPane1.setViewportView(txtaLog);

        pnlBottom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlActions.setLayout(new java.awt.GridLayout(2, 2));

        btnFight.setText("FIGHT");
        btnFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFightActionPerformed(evt);
            }
        });
        pnlActions.add(btnFight);

        btnPKMN.setText("PKMN");
        pnlActions.add(btnPKMN);

        btnQuit.setText("QUIT");
        pnlActions.add(btnQuit);

        pnlBottom.add(pnlActions, java.awt.BorderLayout.LINE_END);

        add(pnlBottom, java.awt.BorderLayout.SOUTH);

        pnlBattle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        pnlBattle.setLayout(new java.awt.BorderLayout());

        pnlUser.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));
        pnlBattle.add(pnlUser, java.awt.BorderLayout.PAGE_END);

        pnlAI.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));
        pnlBattle.add(pnlAI, java.awt.BorderLayout.PAGE_START);

        add(pnlBattle, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFightActionPerformed
        if(logicMan.isUserTurn()){
            JPopupMenu menu = new JPopupMenu("Movimientos");
            Pokemon p = user.getPokemon();
            for(Movement mov : p.getMovimientos()){
                menu.add(new AbstractAction("" + mov) {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        logicMan.getBattle().getEntrenadores().get(0).setNextMove(mov);
                        advanceTurn();
                    }
                });
            }
            menu.show(btnFight, btnFight.getX(), btnFight.getY());
        }   
    }//GEN-LAST:event_btnFightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFight;
    private javax.swing.JButton btnPKMN;
    private javax.swing.JButton btnQuit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAI;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlBattle;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JTextArea txtaLog;
    // End of variables declaration//GEN-END:variables
}
