/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JPanel;
import modelo.Pokemon;
import poketac.PokeTAC;

/**
 *
 * @author Usuario
 */
public class MainWindow extends javax.swing.JFrame {
    PokeTAC logicMan;
    JPanel prevPanel;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        logicMan = new PokeTAC();
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void startBattle(List<Pokemon> userPokemons){
        logicMan.initBattle(userPokemons);
        pnlBackground.remove(prevPanel);
        BattleScreen bscreen = new BattleScreen(this, logicMan);
        prevPanel = bscreen;
        pnlBackground.add(bscreen, BorderLayout.CENTER);
        this.revalidate();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlWelcome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlBackground.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlBackground.setLayout(new java.awt.BorderLayout());

        pnlWelcome.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a PokeTAC");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        txtName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setText("Jugador1");
        jPanel1.add(txtName, java.awt.BorderLayout.CENTER);

        btnStart.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnStart.setText("Comenzar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart, java.awt.BorderLayout.PAGE_END);

        pnlWelcome.add(jPanel1, new java.awt.GridBagConstraints());

        pnlBackground.add(pnlWelcome, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        logicMan.initGame(txtName.getText());
        pnlBackground.remove(pnlWelcome);
        PokemonSelect pnl = new PokemonSelect(this, logicMan.getAllPokemons(), true);
        prevPanel = pnl;
        pnlBackground.add(pnl, BorderLayout.CENTER);
        this.revalidate();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
