/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import modelo.Movement;
import modelo.PokeInfo;
import modelo.Pokemon;
import poketac.PokeTAC;

/**
 *
 * @author Usuario
 */
public class MovementSelect extends javax.swing.JDialog {
    private int index = 0;
    private final List<PokeInfo> pokeinfos;
    private List<Pokemon> pokemons;

    public MovementSelect(java.awt.Frame parent, boolean modal, List<PokeInfo> pokeinfos) {
        super(parent, modal);
        this.pokeinfos = pokeinfos;
        this.pokemons = new ArrayList<>();
        initComponents();
        displayCurrentPokemon();
        setLocationRelativeTo(parent);
    }
    
    private void displayCurrentPokemon(){
        PokeInfo p = pokeinfos.get(index);
        try {
            PokeTAC.loadDataPokeMovements(p);
        }
        catch(IOException e){
            System.out.println("ERROR: PokeMovements loader");
            e.printStackTrace();
        }
        List<Movement> movs = p.getMoves();
        DefaultListModel<Movement> model = new DefaultListModel<>();
        movs.stream().forEach((m) -> {model.addElement(m);});
        jlstMovements.setModel(model);
        lblName.setText(p.getNombre());
        if(index == 3) btnNext.setText("Finalizar");
        else btnNext.setText("Siguiente");
    }
    
    public List<Pokemon> displayMovementSelect(){
        this.setVisible(true);
        if(pokemons.size() == PokeTAC.MAX_POKEMON){
            return pokemons;
        }else{
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstMovements = new javax.swing.JList();
        pnlButtons = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccionar Movimientos");
        setMinimumSize(new java.awt.Dimension(200, 126));

        pnlBackground.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlBackground.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblName.setText("Pikachu");
        lblName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblName);

        pnlBackground.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jlstMovements.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlstMovements);

        pnlBackground.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        btnNext.setText("Siguiente");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlButtons.add(btnNext);
        pnlButtons.add(filler1);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        pnlBackground.add(pnlButtons, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlBackground, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        PokeInfo p = pokeinfos.get(index);
        List<Movement> movs = jlstMovements.getSelectedValuesList();
        if(movs.size()==PokeTAC.MAX_MOVES){
            Pokemon pokemon = new Pokemon(p, movs);
            pokemons.add(pokemon);
            index++;
            if(index<PokeTAC.MAX_POKEMON){
                displayCurrentPokemon();
            }else{
                setVisible(false);
                dispose();
            }           
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovementSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovementSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovementSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovementSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MovementSelect dialog = new MovementSelect(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlstMovements;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlButtons;
    // End of variables declaration//GEN-END:variables
}
