/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.List;
import javax.swing.DefaultListModel;
import modelo.PokeInfo;
import modelo.Pokemon;
import poketac.PokeTAC;

/**
 *
 * @author Usuario
 */
public class PokemonSelect extends javax.swing.JPanel{
    private final boolean selection;
    private final MainWindow mw;


    public PokemonSelect(MainWindow mw, List<PokeInfo> pokemons, boolean selection) {
        initComponents();
        this.mw = mw;
        this.selection = selection;
        if(selection){
            pnlButtons.remove(btnCancel);
            pnlButtons.remove(filler1);
        }
        initList(pokemons);
    }
    
    private void initList(List<PokeInfo> pokemons){
        DefaultListModel<PokeInfo> model = new DefaultListModel<>();
        for(PokeInfo p : pokemons) model.addElement(p);
        jlstPokeList.setModel(model);
        jlstPokeList.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtons = new javax.swing.JPanel();
        btnAccept = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btnCancel = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        jlstPokeList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        btnAccept.setText("Aceptar");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        pnlButtons.add(btnAccept);
        pnlButtons.add(filler1);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        jlstPokeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollPane.setViewportView(jlstPokeList);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        if(selection){
            List<PokeInfo> pokeinfos = jlstPokeList.getSelectedValuesList();
            List<Pokemon> pokemons;
            if(pokeinfos.size()==PokeTAC.MAX_POKEMON){
                MovementSelect movSel = new MovementSelect(mw, true, pokeinfos);
                pokemons = movSel.displayMovementSelect();
                if(pokemons!=null){
                    mw.startBattle(pokemons);
                }
            }
        }  
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JList jlstPokeList;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
